# Generated by Django 6.1.1 on 2026-09-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='photos',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='Listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'country'], name='listing_city_country_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listing_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['deleted_at'], name='listing_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listing_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listing_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='photos',
            index=models.Index(fields=['listing', 'order'], name='photo_listing_order_idx'),
        ),
        migrations.AddIndex(
            model_name='photos',
            index=models.Index(fields=['listing', 'is_main'], name='photo_listing_is_main_idx'),
        ),
    ]
