# Generated by Django 6.1.1 on 2026-09-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_deleted_at_alter_photos_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='Listing'),
        ),
    ]
