# Generated by Django 6.1.1 on 2026-09-13 17:02

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('check_in', models.DateField(validators=[core.validators.validate_not_in_past], verbose_name='Check In')),
                ('check_out', models.DateField(verbose_name='Check Out')),
                ('guests_count', models.PositiveIntegerField(choices=[(1, '1 quest'), (2, '2 quests'), (3, '3 quests'), (4, '4 quests'), (5, '5 quests'), (6, '6 quests'), (7, '7 quests')], default=1, verbose_name='Guests Count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ('-check_in',),
            },
        ),
    ]
